# Generated by Django 4.2.6 on 2023-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIfacturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_metodopago',
            name='codigo_mP',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del metodo de pago'),
        ),
    ]
