# Generated by Django 4.2.6 on 2023-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_reserva',
            name='codigo_res',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de la reserva'),
        ),
    ]
