# Generated by Django 4.2.6 on 2023-11-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuariosGestion', '0005_remove_tb_usuarios_id_tb_usuarios_apellidos_cli_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_reserva',
            fields=[
                ('codigo_res', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la reserva')),
                ('fechaInicio_res', models.DateField(verbose_name='Fecha de inicio')),
                ('fechaSalida_res', models.DateField(verbose_name='Fecha de salida')),
                ('cantidadJovenes_res', models.IntegerField(verbose_name='Cantidad de jovenes')),
                ('cantidadAdultos_res', models.IntegerField(verbose_name='Cantidad de adultos')),
                ('numeroDocumento_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuariosGestion.tb_usuarios', verbose_name='Numero de documento del usuario')),
            ],
        ),
    ]
