# Generated by Django 4.2.6 on 2023-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturasGestion', '0002_alter_tb_factura_fechaemision_fac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_factura',
            name='fechaEmision_fac',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emision de la factura'),
        ),
    ]
