# Generated by Django 4.2.6 on 2023-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=80)),
                ('numeroDocumento', models.IntegerField()),
                ('numeroFicha', models.CharField(max_length=50)),
                ('aprendizFoto', models.ImageField(upload_to='fotosAprendices')),
            ],
        ),
    ]
