INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Sushi',30000,10,5,1,3);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Alitas',36500,100,12,3,7);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Queso Italiano',10000,3,2,2,1);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Arroz Paisa',40000,50,5,4,5);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Costillas BBQ',70000,200,20,5,7);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Bandeja Paisa',25000,35,2,7,6);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Ensalada de Frutas',20000,90,1,6,4);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Desayuno a base de cereales naturales',10000,100,3,8,5);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Bagre sudado',50000,10,1,9,3);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Pepino en salsa',15000,30,5,11,2);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Arroz con pollo',5000,300,20,10,5);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Carne Asada',35000,50,2,12,7);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Bandeja de Frutas',45000,150,1,13,4);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Bol de verdura',60000,90,7,15,2);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Bandeja de lentejas',15000,500,1,14,6);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Conjunto de quesos europeos',30000,40,10,1,1);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Pechuga a la plancha',50000,45,5,2,7);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Mojarra Frita',28000,300,1,3,3);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Garbanzos',5000,400,10,4,6);
INSERT INTO tb_producto (nombre_pro,precioUnitario_pro,unidadesInventario_pro,ordenUnidades_pro,id_pr,id_cat) VALUES ('Pizza Italiana',25000,2000,23,5,7);