# Generated by Django 4.2.6 on 2023-11-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_estado',
            fields=[
                ('codigo_ed', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Codigo del Estado')),
                ('tipo_ed', models.CharField(max_length=70, verbose_name='Tipo de Estado')),
            ],
        ),
        migrations.CreateModel(
            name='tb_tipoHabitacion',
            fields=[
                ('codigo_tpH', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Codigo del tipo de habitacion')),
                ('tipo_tpH', models.CharField(max_length=70, verbose_name='Tipo de habitacion')),
                ('valorBase_tpH', models.FloatField(verbose_name='Valor base del tipo de habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='tb_mobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camasSecillas_im', models.IntegerField(verbose_name='Numero de camas sencillas')),
                ('camasDobles_im', models.IntegerField(verbose_name='Numero de camas dobles')),
                ('camasTriples_im', models.IntegerField(verbose_name='Numero de camas triples')),
                ('camasMatrimoniales_im', models.IntegerField(verbose_name='Numero de camas matrimoniales')),
                ('televisor_im', models.IntegerField(verbose_name='Numero de televisores')),
                ('bano_im', models.IntegerField(verbose_name='Numero de baños')),
                ('escritorio_im', models.IntegerField(verbose_name='Numero de escritorios')),
                ('codigo_tpH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacionesGestion.tb_tipohabitacion', verbose_name='Codigo del tipo de habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='tb_habitacion',
            fields=[
                ('codigo_hab', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la habitacion')),
                ('precio_tpH', models.FloatField(verbose_name='Precio de la habitacion')),
                ('descripcion_tpH', models.TextField(verbose_name='Descripcion de la habitacion')),
                ('minimoPersonas_tpH', models.IntegerField(verbose_name='Minimo de personas')),
                ('maximoPersonas_tpH', models.IntegerField(verbose_name='Maximo de personas')),
                ('image_tpH', models.ImageField(upload_to='fotoHabitaciones')),
                ('codigo_ed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacionesGestion.tb_estado', verbose_name='Codigo del estado')),
                ('codigo_tpH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacionesGestion.tb_tipohabitacion', verbose_name='Codigo del tipo de habitacion')),
            ],
        ),
    ]
