# Generated by Django 4.2.6 on 2023-11-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacionesGestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_habitacion',
            name='precio_tpH',
        ),
    ]
