# Generated by Django 4.2.6 on 2023-11-29 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacionesGestion', '0003_tb_paquetemobiliario_remove_tb_mobiliario_bano_im_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_estado',
            name='codigo_ed',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Codigo del Estado'),
        ),
        migrations.AlterField(
            model_name='tb_habitacion',
            name='codigo_hab',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Codigo de la habitacion'),
        ),
        migrations.AlterField(
            model_name='tb_mobiliario',
            name='codigo_pMb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habitacionesGestion.tb_paquetemobiliario', verbose_name='Codigo del paquete de mobiliario'),
        ),
        migrations.AlterField(
            model_name='tb_paquetemobiliario',
            name='codigo_pMb',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Codigo del paquete'),
        ),
        migrations.AlterField(
            model_name='tb_tipohabitacion',
            name='codigo_tpH',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Codigo del tipo de habitacion'),
        ),
    ]
