# Generated by Django 4.2.6 on 2023-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacionesGestion', '0005_alter_tb_tipohabitacion_codigo_tph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_estado',
            name='codigo_ed',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del Estado'),
        ),
        migrations.AlterField(
            model_name='tb_habitacion',
            name='codigo_hab',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la habitacion'),
        ),
        migrations.AlterField(
            model_name='tb_mobiliario',
            name='codigo_mB',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del mobiliario'),
        ),
        migrations.AlterField(
            model_name='tb_paquetemobiliario',
            name='codigo_pMb',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del paquete'),
        ),
    ]
