# Generated by Django 4.2.6 on 2023-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosGestion', '0002_alter_tb_categoria_codigo_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_categoria',
            name='codigo_cat',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de la categoria'),
        ),
    ]
