# Generated by Django 4.2.6 on 2023-11-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosGestion', '0002_delete_tb_dasd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_usuario',
            new_name='tb_usuarioS',
        ),
    ]
