# Generated by Django 4.2.6 on 2023-11-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuariosGestion', '0004_remove_tb_usuarios_codigo_rl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_usuarios',
            name='id',
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='apellidos_cli',
            field=models.CharField(default='', max_length=50, verbose_name='Apellidos del usuario'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='codigo_rl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuariosGestion.tb_rol', verbose_name='Codigo de rol'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='codigo_tpD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuariosGestion.tb_tpdocumento', verbose_name='Codigo del tipo de documento'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='correoElectronico_clI',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo Electronico'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='nombres_cli',
            field=models.CharField(default='', max_length=50, verbose_name='Nombres Del usuario'),
        ),
        migrations.AddField(
            model_name='tb_usuarios',
            name='numeroDocumento_cli',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='tb_usuarios',
            name='contrasena_cli',
            field=models.CharField(default='', max_length=50, verbose_name='Contraseña del usuario'),
        ),
    ]
