# Generated by Django 4.2.6 on 2023-11-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIservicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_consumo',
            name='numero_con',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del consumo'),
        ),
    ]
