# Generated by Django 4.2.6 on 2023-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIservicios', '0002_alter_tb_consumo_numero_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_categoria',
            name='codigo_cat',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Codigo de la categoria'),
        ),
        migrations.AlterField(
            model_name='tb_servicio',
            name='codigo_ser',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo del servicio'),
        ),
    ]
